// <auto-generated />
using System;
using GrandArchive.Models.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GrandArchive.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250928200517_domains")]
    partial class domains
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.20");

            modelBuilder.Entity("GrandArchive.Models.Database.DndClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPrestige")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MigrationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DndClasses");
                });

            modelBuilder.Entity("GrandArchive.Models.Database.DndClassSpell", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClassId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MigrationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpellId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SpellId");

                    b.HasIndex("ClassId", "SpellId")
                        .IsUnique();

                    b.ToTable("DndClassSpells");
                });

            modelBuilder.Entity("GrandArchive.Models.Database.DndDomain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MigrationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DndDomains");
                });

            modelBuilder.Entity("GrandArchive.Models.Database.DndDomainSpell", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DomainId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MigrationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpellId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SpellId");

                    b.HasIndex("DomainId", "SpellId")
                        .IsUnique();

                    b.ToTable("DndDomainSpells");
                });

            modelBuilder.Entity("GrandArchive.Models.Database.DndEdition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MigrationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("System")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DndEditions");
                });

            modelBuilder.Entity("GrandArchive.Models.Database.DndRulebook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DndEditionId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MigrationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PublishingDay")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PublishingMonth")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PublishingYear")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DndEditionId");

                    b.ToTable("DndRulebooks");
                });

            modelBuilder.Entity("GrandArchive.Models.Database.DndSpell", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AbstinenceComponent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ArcaneFocus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CastingTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ColdfireComponent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CorruptionComponent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomRangeText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DescriptionShort")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Descriptor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DiseaseComponent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DragonmarkComponent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DrugComponent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Effect")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExperienceComponent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtraComponent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasAbstinenceComponent")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasArcaneFocus")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasBreathComponent")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasColdfireComponent")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasCorruptionComponent")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasDiseaseComponent")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasDivineFocus")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasDragonmarkComponent")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasDrugComponent")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasExperienceComponent")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasLocationComponent")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasMaterialComponent")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasMindsetComponent")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasSacrificeComponent")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasSomaticComponent")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasTruenameComponent")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasVerbalComponent")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LocationComponent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MaterialComponent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("MigrationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MindsetComponent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Range")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RulebookId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RulebookPage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SacrificeComponent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SavingThrow")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("School")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SpellResistance")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SubSchool")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TruenameComponent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RulebookId");

                    b.ToTable("DndSpells");
                });

            modelBuilder.Entity("GrandArchive.Models.Database.DndClassSpell", b =>
                {
                    b.HasOne("GrandArchive.Models.Database.DndClass", "Class")
                        .WithMany("ClassSpells")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GrandArchive.Models.Database.DndSpell", "Spell")
                        .WithMany("ClassSpells")
                        .HasForeignKey("SpellId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Spell");
                });

            modelBuilder.Entity("GrandArchive.Models.Database.DndDomainSpell", b =>
                {
                    b.HasOne("GrandArchive.Models.Database.DndDomain", "Domain")
                        .WithMany("DomainSpells")
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GrandArchive.Models.Database.DndSpell", "Spell")
                        .WithMany("DomainSpells")
                        .HasForeignKey("SpellId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Domain");

                    b.Navigation("Spell");
                });

            modelBuilder.Entity("GrandArchive.Models.Database.DndRulebook", b =>
                {
                    b.HasOne("GrandArchive.Models.Database.DndEdition", "DndEdition")
                        .WithMany("Rulebooks")
                        .HasForeignKey("DndEditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DndEdition");
                });

            modelBuilder.Entity("GrandArchive.Models.Database.DndSpell", b =>
                {
                    b.HasOne("GrandArchive.Models.Database.DndRulebook", "Rulebook")
                        .WithMany("Spells")
                        .HasForeignKey("RulebookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rulebook");
                });

            modelBuilder.Entity("GrandArchive.Models.Database.DndClass", b =>
                {
                    b.Navigation("ClassSpells");
                });

            modelBuilder.Entity("GrandArchive.Models.Database.DndDomain", b =>
                {
                    b.Navigation("DomainSpells");
                });

            modelBuilder.Entity("GrandArchive.Models.Database.DndEdition", b =>
                {
                    b.Navigation("Rulebooks");
                });

            modelBuilder.Entity("GrandArchive.Models.Database.DndRulebook", b =>
                {
                    b.Navigation("Spells");
                });

            modelBuilder.Entity("GrandArchive.Models.Database.DndSpell", b =>
                {
                    b.Navigation("ClassSpells");

                    b.Navigation("DomainSpells");
                });
#pragma warning restore 612, 618
        }
    }
}
