// <auto-generated />
using System;
using GrandArchive.Models.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GrandArchive.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250920133902_migrationId")]
    partial class migrationId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.20");

            modelBuilder.Entity("GrandArchive.Models.Database.DndEdition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("MigrationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("System")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DndEditions");
                });

            modelBuilder.Entity("GrandArchive.Models.Database.DndRulebook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DndEditionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MigrationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PublishingDay")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PublishingMonth")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PublishingYear")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DndEditionId");

                    b.ToTable("DndRulebooks");
                });

            modelBuilder.Entity("GrandArchive.Models.Database.DndRulebook", b =>
                {
                    b.HasOne("GrandArchive.Models.Database.DndEdition", "DndEdition")
                        .WithMany("Rulebooks")
                        .HasForeignKey("DndEditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DndEdition");
                });

            modelBuilder.Entity("GrandArchive.Models.Database.DndEdition", b =>
                {
                    b.Navigation("Rulebooks");
                });
#pragma warning restore 612, 618
        }
    }
}
