// <auto-generated />
using System;
using GrandArchive.Models.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GrandArchive.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250921003224_updatedAt")]
    partial class updatedAt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.20");

            modelBuilder.Entity("GrandArchive.Models.Database.DndEdition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MigrationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("System")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DndEditions");
                });

            modelBuilder.Entity("GrandArchive.Models.Database.DndRulebook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DndEditionId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MigrationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PublishingDay")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PublishingMonth")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PublishingYear")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DndEditionId");

                    b.ToTable("DndRulebooks");
                });

            modelBuilder.Entity("GrandArchive.Models.Database.DndSpell", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CastingTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CorruptionComponent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomRangeText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DescriptionShort")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Descriptor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Effect")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExperienceComponent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtraComponent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasArcaneFocus")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasBreathComponent")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasCorruptionComponent")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasDivineFocus")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasExperienceComponent")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasMaterialComponent")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasSomaticComponent")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasTruenameComponent")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasVerbalComponent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MaterialComponent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("MigrationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Range")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RulebookId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RulebookPage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SavingThrow")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("School")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SpellResistance")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SubSchool")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RulebookId");

                    b.ToTable("DndSpells");
                });

            modelBuilder.Entity("GrandArchive.Models.Database.DndRulebook", b =>
                {
                    b.HasOne("GrandArchive.Models.Database.DndEdition", "DndEdition")
                        .WithMany("Rulebooks")
                        .HasForeignKey("DndEditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DndEdition");
                });

            modelBuilder.Entity("GrandArchive.Models.Database.DndSpell", b =>
                {
                    b.HasOne("GrandArchive.Models.Database.DndRulebook", "Rulebook")
                        .WithMany()
                        .HasForeignKey("RulebookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rulebook");
                });

            modelBuilder.Entity("GrandArchive.Models.Database.DndEdition", b =>
                {
                    b.Navigation("Rulebooks");
                });
#pragma warning restore 612, 618
        }
    }
}
